name: assignment_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  data_table_2: ^2.7.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  i18n_extension: ^15.1.0
  i18n_extension_importer: ^0.0.6
  json_annotation: ^4.9.0
  lottie: ^3.3.2
  reactive_dropdown_search: ^6.0.0-pre4
  reactive_forms: ^18.2.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: 3.2.0
  json_serializable: ^6.11.2

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
    - family: Almarai
      fonts:
        - asset: assets/fonts/almarai/Almarai-Light.ttf
          weight: 200
        - asset: assets/fonts/almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/almarai/Almarai-ExtraBold.ttf
          weight: 800
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/translations/
    - .env
